"""Multi-format scientific documentation compiler.

Emits the same audit as clean Markdown (`.md`), a line-numbered A4 Word document
(`.docx`, black text, Springer-Nature-style headings, figureless), and a LaTeX
source (`.tex`). The workflow flowchart is rendered natively in each format
(python-docx tables for Word, a TikZ node chain for LaTeX, a Mermaid block plus
an ASCII fallback for Markdown) rather than by rasterizing an image, so no image
toolchain is required.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from omicau.reporting.reporter import FLOWCHART_STEPS, flowchart_mermaid


# --------------------------------------------------------------------------- #
# Shared content extraction
# --------------------------------------------------------------------------- #
def _fmt(v: Any, nd: int = 4) -> str:
    if v is None:
        return "n/a"
    if isinstance(v, float):
        return f"{v:.{nd}g}"
    return str(v)


def _model_table_rows(models: dict) -> tuple[list[str], list[list[str]]]:
    metric = models.get("primary_metric", "score")
    header = ["Model", "Type", metric.upper(), "±std", "Features", "Folds"]
    allr = list(models.get("classical", [])) + list(models.get("neural", {}).get("results", []))
    allr += list(models.get("controls", []))
    rows = []
    for r in allr:
        typ = ("control" if r["name"].startswith("control::")
               else "fusion" if r["name"].endswith("FUSION")
               else "leave-one-out" if "FUSION-minus-" in r["name"]
               else "single")
        rows.append([r["name"], typ, _fmt(r.get("primary")), _fmt(r.get("primary_std")),
                     str(r.get("n_features")), str(r.get("n_splits"))])
    return header, rows


def _ledger_rows(util: dict) -> tuple[list[str], list[list[str]]]:
    header = ["Modality", "Feat.", "Standalone", "Marginal gain", "CKA (partner)", "Verdict"]
    rows = []
    for m in util.get("modality_ledger", []):
        rows.append([m["modality"], str(m.get("n_features")),
                     _fmt(m.get("standalone_primary")), _fmt(m.get("marginal_gain_classical")),
                     f"{_fmt(m.get('redundancy_max_cka'),2)} ({m.get('redundant_with') or '—'})",
                     m.get("verdict", "")])
    return header, rows


# --------------------------------------------------------------------------- #
# Markdown
# --------------------------------------------------------------------------- #
def _md_table(header: list[str], rows: list[list[str]]) -> str:
    line = "| " + " | ".join(header) + " |"
    sep = "| " + " | ".join(["---"] * len(header)) + " |"
    body = "\n".join("| " + " | ".join(str(c) for c in r) + " |" for r in rows)
    return "\n".join([line, sep, body])


def _build_markdown(audit: dict) -> str:
    meta = audit.get("meta", {})
    ds = audit.get("dataset", {})
    util = audit.get("utility", {})
    models = audit.get("models", {})
    summary = audit.get("summary", {})
    miss = audit.get("diagnostics", {}).get("missingness", {})
    batch = audit.get("diagnostics", {}).get("batch", {})
    env = audit.get("environment", {})
    cost = audit.get("cost_estimate", {})

    L: list[str] = []
    L.append(f"# omicau audit — {meta.get('run_name','')}\n")
    L.append(f"*Generated by omicau v{meta.get('tool_version','')} on {meta.get('created','')}.*\n")
    L.append("## 1. Provenance\n")
    L.append(f"- **SHA-256 provenance hash:** `{meta.get('provenance_hash','')}`")
    L.append(f"- **Seed:** {meta.get('seed')} · **Device:** {meta.get('device')} · "
             f"**Cores:** {meta.get('cores')}")
    L.append(f"- **Estimated wall-time:** {cost.get('human_readable','n/a')}\n")

    L.append("## 2. Dataset\n")
    L.append(f"- **Task:** {ds.get('task')} · **Samples aligned:** {ds.get('n_samples')} "
             f"· **Dropped (missing endpoint):** {ds.get('n_dropped',0)}")
    if ds.get("class_balance"):
        L.append(f"- **Class balance:** {ds.get('class_balance')}")
    mh = ["Modality", "Features", "Description"]
    mr = [[m["name"], str(m["n_features"]), m.get("description", "")] for m in ds.get("modalities", [])]
    L.append("\n" + _md_table(mh, mr) + "\n")

    L.append("## 3. Executive summary\n")
    L.append(f"**Data-hygiene rating:** {summary.get('data_hygiene_rating','n/a')}\n")
    L.append(f"{summary.get('clinical_verdict','')}\n")
    recs = summary.get("actionable_recommendations", [])
    if recs:
        L.append("**Recommendations:**\n")
        L.extend(f"- {r}" for r in recs)
        L.append("")

    L.append("## 4. Modality utility ledger\n")
    lh, lr = _ledger_rows(util)
    L.append(_md_table(lh, lr) + "\n")
    if util.get("fusion_gain_over_best_single") is not None:
        L.append(f"Fusion gain over the best single modality: "
                 f"**{util['fusion_gain_over_best_single']:+.3f}** "
                 f"({models.get('primary_metric','')}).\n")

    L.append("## 5. Cross-modal performance\n")
    ph, pr = _model_table_rows(models)
    L.append(_md_table(ph, pr) + "\n")

    L.append("## 6. Data-hygiene diagnostics\n")
    allflags = miss.get("flags", []) + batch.get("flags", [])
    if allflags:
        L.extend(f"- ⚠ {f}" for f in allflags)
    else:
        L.append("- No missingness-bias or batch-effect flags raised.")
    L.append("")

    L.append("## 7. Feature attribution (leakage-safe)\n")
    fusion = next((r for r in models.get("classical", []) if r["name"].endswith("::FUSION")
                   and r.get("feature_importance")), None)
    if fusion:
        top = sorted(fusion["feature_importance"].items(), key=lambda kv: kv[1], reverse=True)[:15]
        L.append(_md_table(["Rank", "Feature", "Importance"],
                           [[i + 1, k, _fmt(v)] for i, (k, v) in enumerate(top)]) + "\n")

    L.append("## 8. Workflow\n")
    L.append("```mermaid\n" + flowchart_mermaid() + "\n```\n")
    L.append("_ASCII fallback:_\n\n```")
    L.append("\n   |\n   v\n".join(f"[ {t} ]" for t, _s, _c in FLOWCHART_STEPS))
    L.append("```\n")

    L.append("## 9. Environment\n")
    L.append(f"- Python {env.get('python')} · torch {env.get('torch')} · "
             f"numpy {env.get('numpy')}")
    L.append(f"- Platform: {env.get('platform')} ({env.get('machine')})\n")
    return "\n".join(L)


# --------------------------------------------------------------------------- #
# DOCX (A4, line-numbered, black text)
# --------------------------------------------------------------------------- #
def _docx_black(style) -> None:
    from docx.shared import RGBColor
    try:
        style.font.color.rgb = RGBColor(0, 0, 0)
    except Exception:  # noqa: BLE001
        pass


def _add_line_numbers(section) -> None:
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    sectPr = section._sectPr
    ln = sectPr.find(qn("w:lnNumType"))
    if ln is None:
        ln = OxmlElement("w:lnNumType")
        sectPr.append(ln)
    ln.set(qn("w:countBy"), "1")
    ln.set(qn("w:restart"), "continuous")
    ln.set(qn("w:distance"), "360")


def _docx_table(doc, header, rows):
    table = doc.add_table(rows=1, cols=len(header))
    try:
        table.style = "Table Grid"
    except KeyError:  # pragma: no cover - template without the style
        pass
    for i, h in enumerate(header):
        cell = table.rows[0].cells[i]
        cell.text = str(h)
        for p in cell.paragraphs:
            for run in p.runs:
                run.bold = True
    for r in rows:
        cells = table.add_row().cells
        for i, v in enumerate(r):
            cells[i].text = str(v)
    return table


def _build_docx(audit: dict, path: Path) -> None:
    from docx import Document
    from docx.shared import Mm, Pt

    meta = audit.get("meta", {})
    ds = audit.get("dataset", {})
    util = audit.get("utility", {})
    models = audit.get("models", {})
    summary = audit.get("summary", {})
    miss = audit.get("diagnostics", {}).get("missingness", {})
    batch = audit.get("diagnostics", {}).get("batch", {})
    env = audit.get("environment", {})
    cost = audit.get("cost_estimate", {})

    doc = Document()
    # A4 page + margins + black body + line numbers.
    for section in doc.sections:
        section.page_height = Mm(297)
        section.page_width = Mm(210)
        section.left_margin = section.right_margin = Mm(25)
        section.top_margin = section.bottom_margin = Mm(25)
        _add_line_numbers(section)
    normal = doc.styles["Normal"]
    normal.font.name = "Times New Roman"
    normal.font.size = Pt(11)
    _docx_black(normal)
    for sname in ("Heading 1", "Heading 2", "Heading 3", "Title"):
        try:
            _docx_black(doc.styles[sname])
        except KeyError:
            pass

    doc.add_heading(f"omicau audit — {meta.get('run_name','')}", level=0)
    doc.add_paragraph(f"Generated by omicau v{meta.get('tool_version','')} on {meta.get('created','')}.")

    doc.add_heading("1. Provenance", level=1)
    doc.add_paragraph(f"SHA-256 provenance hash: {meta.get('provenance_hash','')}")
    doc.add_paragraph(f"Seed {meta.get('seed')} · device {meta.get('device')} · "
                      f"cores {meta.get('cores')} · est. wall-time {cost.get('human_readable','n/a')}")

    doc.add_heading("2. Dataset", level=1)
    doc.add_paragraph(f"Task: {ds.get('task')}; samples aligned: {ds.get('n_samples')}; "
                      f"dropped (missing endpoint): {ds.get('n_dropped',0)}; "
                      f"class balance: {ds.get('class_balance')}")
    _docx_table(doc, ["Modality", "Features", "Description"],
                [[m["name"], m["n_features"], m.get("description", "")] for m in ds.get("modalities", [])])

    doc.add_heading("3. Executive summary", level=1)
    doc.add_paragraph(f"Data-hygiene rating: {summary.get('data_hygiene_rating','n/a')}")
    doc.add_paragraph(summary.get("clinical_verdict", ""))
    if summary.get("actionable_recommendations"):
        doc.add_heading("Recommendations", level=2)
        for r in summary["actionable_recommendations"]:
            doc.add_paragraph(str(r), style="List Bullet")

    doc.add_heading("4. Modality utility ledger", level=1)
    lh, lr = _ledger_rows(util)
    _docx_table(doc, lh, lr)

    doc.add_heading("5. Cross-modal performance", level=1)
    ph, pr = _model_table_rows(models)
    _docx_table(doc, ph, pr)

    doc.add_heading("6. Data-hygiene diagnostics", level=1)
    flags = miss.get("flags", []) + batch.get("flags", [])
    if flags:
        for f in flags:
            doc.add_paragraph(str(f), style="List Bullet")
    else:
        doc.add_paragraph("No missingness-bias or batch-effect flags raised.")

    doc.add_heading("7. Feature attribution (leakage-safe)", level=1)
    fusion = next((r for r in models.get("classical", []) if r["name"].endswith("::FUSION")
                   and r.get("feature_importance")), None)
    if fusion:
        top = sorted(fusion["feature_importance"].items(), key=lambda kv: kv[1], reverse=True)[:15]
        _docx_table(doc, ["Rank", "Feature", "Importance"],
                    [[i + 1, k, _fmt(v)] for i, (k, v) in enumerate(top)])

    doc.add_heading("8. Workflow", level=1)
    flow = doc.add_table(rows=0, cols=1)
    try:
        flow.style = "Table Grid"
    except KeyError:
        pass
    for i, (title, sub, _c) in enumerate(FLOWCHART_STEPS):
        cell = flow.add_row().cells[0]
        cell.paragraphs[0].add_run(title).bold = True
        cell.add_paragraph(sub)
        if i < len(FLOWCHART_STEPS) - 1:
            doc.add_paragraph("↓")

    doc.add_heading("9. Environment", level=1)
    doc.add_paragraph(f"Python {env.get('python')} · torch {env.get('torch')} · "
                      f"numpy {env.get('numpy')} · {env.get('platform')} ({env.get('machine')})")
    doc.save(str(path))


# --------------------------------------------------------------------------- #
# LaTeX
# --------------------------------------------------------------------------- #
def _tex_escape(s: Any) -> str:
    s = str(s)
    repl = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
            "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
            "^": r"\textasciicircum{}"}
    for k, v in repl.items():
        s = s.replace(k, v)
    return s


def _tex_table(header, rows, colspec=None) -> str:
    ncol = len(header)
    colspec = colspec or ("l" + "r" * (ncol - 1))
    out = [r"\begin{center}", r"\small", f"\\begin{{tabular}}{{{colspec}}}", r"\hline"]
    out.append(" & ".join(rf"\textbf{{{_tex_escape(h)}}}" for h in header) + r" \\ \hline")
    for r in rows:
        out.append(" & ".join(_tex_escape(c) for c in r) + r" \\")
    out += [r"\hline", r"\end{tabular}", r"\end{center}"]
    return "\n".join(out)


def _tex_flowchart() -> str:
    nodes = []
    for i, (title, _sub, _c) in enumerate(FLOWCHART_STEPS):
        below = f"below=of S{i-1}" if i > 0 else ""
        nodes.append(f"\\node[flowbox{(', ' + below) if below else ''}] (S{i}) {{{_tex_escape(title)}}};")
    arrows = "\n".join(f"\\draw[->] (S{i-1}) -- (S{i});" for i in range(1, len(FLOWCHART_STEPS)))
    return (
        "\\begin{center}\n\\begin{tikzpicture}[node distance=8mm,\n"
        "  flowbox/.style={draw,rounded corners,align=center,text width=0.72\\linewidth,"
        "inner sep=5pt}]\n"
        + "\n".join(nodes) + "\n" + arrows + "\n\\end{tikzpicture}\n\\end{center}"
    )


def _build_latex(audit: dict) -> str:
    meta = audit.get("meta", {})
    ds = audit.get("dataset", {})
    util = audit.get("utility", {})
    models = audit.get("models", {})
    summary = audit.get("summary", {})
    miss = audit.get("diagnostics", {}).get("missingness", {})
    batch = audit.get("diagnostics", {}).get("batch", {})
    env = audit.get("environment", {})
    cost = audit.get("cost_estimate", {})

    P: list[str] = []
    P.append(r"\documentclass[11pt]{article}")
    P.append(r"\usepackage[a4paper,margin=25mm]{geometry}")
    P.append(r"\usepackage{array}\usepackage{longtable}\usepackage{tikz}")
    P.append(r"\usetikzlibrary{positioning,arrows.meta}")
    P.append(r"\usepackage{lineno}\usepackage[hidelinks]{hyperref}")
    P.append(r"\usepackage{parskip}")
    P.append(r"\title{omicau audit --- " + _tex_escape(meta.get("run_name", "")) + r"}")
    P.append(r"\date{" + _tex_escape(meta.get("created", "")) + r"}")
    P.append(r"\begin{document}\linenumbers\maketitle")

    P.append(r"\section{Provenance}")
    P.append(r"\texttt{SHA-256: " + _tex_escape(meta.get("provenance_hash", "")) + r"}\\")
    P.append(f"Seed {meta.get('seed')}, device {_tex_escape(meta.get('device'))}, "
             f"cores {meta.get('cores')}, est.\\ wall-time {_tex_escape(cost.get('human_readable','n/a'))}.")

    P.append(r"\section{Dataset}")
    P.append(f"Task: {_tex_escape(ds.get('task'))}; samples aligned: {ds.get('n_samples')}; "
             f"dropped: {ds.get('n_dropped',0)}; class balance: {_tex_escape(ds.get('class_balance'))}.")
    P.append(_tex_table(["Modality", "Features", "Description"],
                        [[m["name"], m["n_features"], m.get("description", "")]
                         for m in ds.get("modalities", [])], colspec="lrp{0.5\\linewidth}"))

    P.append(r"\section{Executive summary}")
    P.append(r"\textbf{Data-hygiene rating:} " + _tex_escape(summary.get("data_hygiene_rating", "n/a")) + r"\\")
    P.append(_tex_escape(summary.get("clinical_verdict", "")))
    if summary.get("actionable_recommendations"):
        P.append(r"\begin{itemize}")
        P.extend(r"\item " + _tex_escape(r_) for r_ in summary["actionable_recommendations"])
        P.append(r"\end{itemize}")

    P.append(r"\section{Modality utility ledger}")
    lh, lr = _ledger_rows(util)
    P.append(_tex_table(lh, lr, colspec="lrrrl p{0.24\\linewidth}"))

    P.append(r"\section{Cross-modal performance}")
    ph, pr = _model_table_rows(models)
    P.append(_tex_table(ph, pr, colspec="llrrrr"))

    P.append(r"\section{Data-hygiene diagnostics}")
    flags = miss.get("flags", []) + batch.get("flags", [])
    if flags:
        P.append(r"\begin{itemize}")
        P.extend(r"\item " + _tex_escape(f) for f in flags)
        P.append(r"\end{itemize}")
    else:
        P.append("No missingness-bias or batch-effect flags raised.")

    P.append(r"\section{Workflow}")
    P.append(_tex_flowchart())

    P.append(r"\section{Environment}")
    P.append(f"Python {_tex_escape(env.get('python'))}, torch {_tex_escape(env.get('torch'))}, "
             f"numpy {_tex_escape(env.get('numpy'))}; {_tex_escape(env.get('platform'))}.")
    P.append(r"\end{document}")
    return "\n".join(P)


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #
def build_documentation(audit: dict, out_dir: str | Path, config=None,
                        formats: list[str] | None = None) -> dict[str, Path]:
    """Write the audit as .md / .docx / .tex (per ``formats``)."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    formats = formats or ["md", "docx", "tex"]
    written: dict[str, Path] = {}

    if "md" in formats:
        p = out / "report.md"
        p.write_text(_build_markdown(audit), encoding="utf-8", newline="")
        written["md"] = p
    if "tex" in formats:
        p = out / "report.tex"
        p.write_text(_build_latex(audit), encoding="utf-8", newline="")
        written["tex"] = p
    if "docx" in formats:
        p = out / "report.docx"
        try:
            _build_docx(audit, p)
            written["docx"] = p
        except Exception as exc:  # noqa: BLE001 - docx is best-effort
            (out / "report_docx_error.txt").write_text(
                f"DOCX generation failed: {exc}\n", encoding="utf-8", newline="")
    return written
